services:
  - type: web
    name: zerodha-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: zerodha-dashboard
    env: static
    buildCommand: cd dashboard && npm install && npm run build
    staticPublishPath: dashboard/build

  - type: web
    name: zerodha-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build