services:
  - type: web
    name: zerodha-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://zerodha-backend-jq1f.onrender.com